env:
  global:
    - CC_TEST_REPORTER_ID=d4bfc623b541efcc21f1e735a27a37297ab138fde061f7c4b35f79b6dd22aa43


language: node_js
sudo: false
node_js:
  - stable


branches:
  only:
    - master
before_script:
  - npm install codeclimate-test-reporter -g
before_install:
  - |
    # Check commit matches expected commit (because of Travis bug)
    ( set -euo pipefail
      if [[ "${TRAVIS_COMMIT}" != "$(git rev-parse HEAD)" ]]; then
        echo "Commit $(git rev-parse HEAD) doesn't match expected commit ${TRAVIS_COMMIT}"
        git checkout "${TRAVIS_COMMIT}"
      fi
    )
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
